name: dev

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1.2.0
        with:
          jvm: temurin:1.21
          apps: sbt
      - uses: coursier/cache-action@v6

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: "22.15.0"
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm@10.9.2

      - name: Build Backend
        working-directory: backend
        run: |
          sbt clean
          sbt test:compile

      - name: Tests Backend
        working-directory: backend
        run: sbt test

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Test Frontend
        working-directory: frontend
        run: npm run test

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-dev
